### ISSUE TITLE
Add Solid Cross platform Build System

### ISSUE THREAD

**Issue by mtangoo** [mtangoo/wxDatabase#2]
Create Build System for wxDB

**Comment by manyleaves** [comment]
From what I can tell, wxWidgets itself has gone to CMake so I guess it makes sense to use CMake instead of bakefile. I've made several attempts to get CMake going for my builds but with no real success. I tried to convert my vc_9 projects using vcproj2cmake but (at the time) chose to hand-write my vc_11 projects instead of learning all the innards of CMake. Maybe someone else already has the experience with CMake to get a first draft of a CMakeLists.txt! I'd be happy to test the Visual Studio projects it creates.

**Comment by patlkli** [comment]
wxWidgets still uses Bakefile for project generation. Since Bakefile 1.x however, they're kinda stuck.
The new version still lacks some required features and requires a complete rewrite of the bakefiles because the syntax is completely different. Nobody has the knowledge and time to do those changes.

A switch to CMake is also discussed, but since it should be backwards compatible, there is quite a lot of effort involved.

I already did some work on some Bakefiles for wxDatabase and I try to look into them this evening and check if they are ready to be released to the public.

However, I also have a lot of projects using CMake and my impression is, that in comparison to Bakefile, it's much more mature and stable.
I think, CMake would be the best solution in the long term.

**Comment by mtangoo** [comment]
@patlkli I'm glad to see you again.
I agree with you on all points. I have one request though. You can release them even if they are not ready and say what is missing. Someone can pick from there and finish it up.
@manyleaves  what do you think of this?

**Comment by mtangoo** [comment]
@manyleaves  I missed your comment. I will try to get CMake working with MySQL. I hope that will be good one to serve as template. Meanwhile, @patlkli will update us on Bakefile status, if its ready for release and then we can use it while we look into CMake as the future

**Comment by mtangoo** [comment]
I just pushed up initial support for CMake, that supports MySQL only for now. Can you guys test and see if it works fine with VS?
@manyleaves @patlkli

**Comment by mtangoo** [comment]
We are going with CMake. b6b8a5a8f4456f7a122137afd7a49c61e16a89f9 already fixes this and provides skeleton for others. Support for different DB should got to different issues
